### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by andrey4545** [uzyandev/pmmp-installer#1]
**При любом вводе версии PocketMine-MP скачивается последняя!**

P.S. I don't know English!

**Comment by uzyandev** [comment]
> **При любом вводе версии PocketMine-MP скачивается последняя!**
> 
> P.S. I don't know English!

Lssue resolved! Wait to new commit

**Comment by Andrey4343** [comment]
**Problem still exists**

**Comment by uzyandev** [comment]
> **Problem still exists**

Proglem was solved in new commit
